### ISSUE TITLE
hatch visual tool not working

### ISSUE THREAD

**Issue by ilfakiro** [jamsoft/uap-data-vis-tool#2]
hello ,
I have downloaded and opened your tool but it's seem incomplete: I cannot see the button "load hatch data", so I cannot use it.
my email is: ilfakiro@libero.it, please let me know how to fix it.
thanks!

**Comment by jamsoft** [comment]
There isn't anything I can do with this report really.

Could you take a screenshot?

**Comment by ilfakiro** [comment]
in attachment: as you can see there is not button "load hatch data".

thanks

**Comment by ilfakiro** [comment]
![screenshot ](https://user-images.githubusercontent.com/28871714/226713641-f5ffb584-c33f-4e7d-b2bf-4d77bb0c9355.jpg)
mail sent

**Comment by jamsoft** [comment]
Wow. OK. That is really odd.

What OS are you running this on? Do you have any non-standard themes configured or installed? Will investigate, thanks for the report.

**Comment by jamsoft** [comment]
I've recreated the issue, it's actually the Windows Light Theme. Try switching to Dark Theme.

I'll work on a fix.

**Comment by jamsoft** [comment]
This issue should now be fixed. Download the tool again and try v.1.1.1.

Let me know how you get on.

**Comment by ilfakiro** [comment]
hello thanks for your replies: I have download the new version, but I still don't see the button "load hatch data":
![image](https://user-images.githubusercontent.com/28871714/226865359-eac0a9df-6595-402e-b06f-dfd3360c1f04.png)

**Comment by ilfakiro** [comment]
hello,

I have just replied: not working yet, still lacking "load hatch data" button....

**Comment by jamsoft** [comment]
What size screen are you using on your machine? What do you have the resolution set to?

**Comment by ilfakiro** [comment]
as adviced by windows, 1920x1080

**Comment by jamsoft** [comment]
I've just release v1.2.0, this should address this issue for you. Let me know how you get on.

**Comment by ilfakiro** [comment]
it works!

thanks!

**Comment by jamsoft** [comment]
Excellent news. I'll close this ticket now. Thanks for your help.

**Comment by ilfakiro** [comment]
thanks again: tomorrow I'll run it and a take a deep view.

ciao

**Comment by jamsoft** [comment]
Have just published another update ... :)

**Comment by ilfakiro** [comment]
great!
